name: core_server
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  http: ^0.13.0
  shelf: ^1.1.0
  jose: ^0.3.2
  oauth2:
    git:
      url: https://github.com/d3roch4/oauth2.git
      ref: master
  domain_core:
    git: 
      url: https://github.com/precastapp/core_module.git
      path: packages/core_domain
      ref: main

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
